version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: habitly-frontend
    working_dir: /app/
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run serve
    ports:
      - 8080:8080
    networks:
    - habitly

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: habitly-backend
    restart: unless-stopped
    environment:
      SECRET_KEY: 'django-insecure-dt)jxs-heeq+x$@@m6j%dxy*seqdm@8wk_%y7le_4ai8w4d%uf'
      ALLOWED_HOSTS: '.0xali.com,localhost'
      JWT_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALi9i9aYA1ktUOE2oYFq7M0V8RWe84gC\nALAj0DxnFiOfJ3pTDxZ1JA+ag6gFCCWtiKMSjDwkDX6C6bK87hdnFU8CAwEAAQ==\n-----END PUBLIC KEY-----"
      JWT_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----\nMIIBOQIBAAJBALi9i9aYA1ktUOE2oYFq7M0V8RWe84gCALAj0DxnFiOfJ3pTDxZ1\nJA+ag6gFCCWtiKMSjDwkDX6C6bK87hdnFU8CAwEAAQJAKCHdKAAb8hp7EIHKsg+l\nY6QZnGXMZ8ZvmdQd35FRaOlCr2CuZ8xVAOicscttVAg3h9Gbwc87WxDwEu+bGCHp\nSQIhANvCOJXNj0ysjBJiNFS6Ds1hfe0EcAOvVzwYdsqMATATAiEA1zTsUdM7mQqY\nYmB6tkVq/TYEHR2BM8EanIEyIAZfRVUCIF4QYFAe0LutD7e+uU+a5EMc+928DIZH\nQzvB7Pb9vnRpAiBejVgPE1mqAee1wWHo11MMcUEZca8kiAEjJfhZ7bLKCQIgLxOO\nz9hpXeSZNT8EItIn6Ah7rEFlQMok9JJH7dE4Zhc=\n-----END RSA PRIVATE KEY-----"
      DB_NAME: 'habitly'
      DB_USERNAME: 'habitly'
      DB_PASSWORD: 'password'
      DB_HOST: 'db'
      DB_PORT: '3306'
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    working_dir: /app/
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - habitly

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: habitly-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'habitly'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_PASSWORD: 'password'
      MYSQL_USER: 'habitly'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER -p$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    networks:
      - habitly

  phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin
      environment:
      - PMA_HOST=db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      restart: unless-stopped
      ports:
      - 8081:80
      networks:
      - habitly

volumes:
  db:

networks:
  habitly:
    driver: bridge